@startuml

actor DA as "Data Analyst"

actor DT as "Development team"


rectangle Database

rectangle "DA System" {
 usecase UC1 as "Generate report
  on Population
 by field"
 usecase UC2 as "Generate report
  for top
 populated countries
  by field"
 usecase UC3 as "Generate report
  on population of
 all cities"
 usecase UC4 as "Generate report
                   on  population
 for specific
 number of cities"
 usecase UC5 as "Generate report
                   on  Population
 of capital cities"
 usecase UC6 as "Generate report
                   on  population
 for specific number
 of capital cities"
 usecase UC7 as "Retrieve info about
 population"
 usecase UC8 as "Make access
 to overall
 population info"
 usecase UC9 as "Make access
 to data about
 languages spoken"





   DA - UC1
   DA - UC2
   DA - UC3
   DA - UC4
   DA - UC5
   DA - UC6
   DA - UC7
   DT - UC8
   DT - UC9


   UC2 ..> UC1 : extend

   UC4 ..>UC3 : extend

   UC6 ..> UC5 : extend



   UC1 - Database

   UC3 - Database
   UC4 - Database
   UC5 - Database
   UC6 - Database
   UC7 - Database



}

@enduml